module.exports = {
  errors: {
    WALK_ERROR: 'WALK_ERROR',
    FIREBASE_ERROR: 'FIREBASE_ERROR',
    PACKAGE_INSTALL_ERROR: 'PACKAGE_INSTALL_ERROR',
    VENDOR_COMPILER_ERROR: 'VENDOR_COMPILER_ERROR',
    SCRIPT_INJECT_ERROR: 'SCRIPT_INJECT_ERROR',
    BUNDLE_ERROR: 'BUNDLE_ERROR',
  },
}